# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='identifier',
            field=models.CharField(default='study1', max_length=150),
            preserve_default=False,
        ),
    ]
