# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_studies_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studies',
            old_name='identifier',
            new_name='creator',
        ),
    ]
