# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_profile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('mtf', 'MtF Female'), ('ftm', 'FtM Male')], max_length=3, null=True, verbose_name='Identified Sex'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
    ]
