# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170211_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='sex',
        ),
    ]
