# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20170211_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True, help_text='weight in kilograms', null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, help_text='height in cm', null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('mtf', 'MtF Female'), ('ftm', 'FtM Male'), ('oth', 'Other')], max_length=3, null=True, verbose_name='Identified Sex'),
        ),
    ]
