# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20170211_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studies',
            name='id',
        ),
        migrations.AlterField(
            model_name='studies',
            name='creator',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
