# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20170211_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.Profile'),
        ),
    ]
