# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_studies_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='hmm', max_length=150, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
