# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20170211_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='creator',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studies',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
